function ExampleTemplate() {
  return `
  <!DOCTYPE html><html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en"><head><title></title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]--><!--[if !mso]><!--><link href="https://fonts.googleapis.com/css?family=Roboto"
  rel="stylesheet" type="text/css"><link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css"><!--<![endif]--><style>
  *{box-sizing:border-box}body{margin:0;padding:0}a[x-apple-data-detectors]{color:inherit!important;text-decoration:inherit!important}#MessageViewBody a{color:inherit;text-decoration:none}p{line-height:inherit}.desktop_hide,.desktop_hide table{mso-hide:all;display:none;max-height:0;overflow:hidden}@media (max-width:620px){.image_block img.big,.row-content{width:100%!important}.mobile_hide{display:none}.stack .column{width:100%;display:block}.mobile_hide{min-height:0;max-height:0;max-width:0;overflow:hidden;font-size:0}.desktop_hide,.desktop_hide table{display:table!important;max-height:none!important}}
  </style></head><body style="background-color:#f5f5f6;margin:0;padding:0;-webkit-text-size-adjust:none;text-size-adjust:none"><table class="nl-container" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#f5f5f6"><tbody><tr><td><table class="row row-1" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table
  class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;border-radius:0;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-1" width="100%"
  border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center" style="line-height:10px"><a href="#"
  style="display:block;height:auto;border:0;width:600px;max-width:100%" width="600"></a></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-2" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation"
  style="mso-table-lspace:0;mso-table-rspace:0;border-radius:0;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#004e87;padding-left:40px;padding-right:40px;vertical-align:top;padding-top:30px;padding-bottom:30px;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="heading_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0"
  role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="text-align:center;width:100%"><h1 style="margin:0;color:#fff;direction:ltr;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif;font-size:27px;font-weight:400;letter-spacing:normal;line-height:120%;text-align:center;margin-top:0;margin-bottom:0"><strong>Falta pouco para resolver seus débitos!</strong><strong><br></strong></h1></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table
  class="row row-3" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%"
  style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#fff;padding-left:40px;padding-right:40px;vertical-align:top;padding-top:0;padding-bottom:0;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="divider_block block-1" width="100%" border="0" cellpadding="20" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad"><div class="alignment" align="center"><table border="0" cellpadding="0"
  cellspacing="0" role="presentation" width="100%" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="divider_inner" style="font-size:1px;line-height:1px;border-top:0 solid #bbb"><span>&#8202;</span></td></tr></table></div></td></tr></table><table class="text_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div
  class="txtTinyMce-wrapper" style="font-size:14px;mso-line-height-alt:16.8px;color:#2b2b2b;line-height:1.2;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif"><p style="margin:0;font-size:18px;letter-spacing:normal"><span style="font-size:18px;">Oi, motorista.<br></span></p><p style="margin:0;font-size:18px;letter-spacing:normal;mso-line-height-alt:16.8px">&nbsp;</p><p style="margin:0;font-size:18px;letter-spacing:normal">
  <span style="font-size:18px;">Vi que você fez um pedido de Teste no Jyula.&nbsp;</span></p><p style="margin:0;font-size:18px;letter-spacing:normal;mso-line-height-alt:16.8px">&nbsp;</p><p style="margin:0;font-size:18px;letter-spacing:normal"><span style="font-size:18px;">Agora, é só concluir o pagamento que a gente avisa quando o seu CRLV estiver disponível no App, beleza?</span></p></div></div></td></tr></table><table class="divider_block block-3"
  width="100%" border="0" cellpadding="20" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad"><div class="alignment" align="center"><table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="divider_inner" style="font-size:1px;line-height:1px;border-top:0 solid #bbb"><span>&#8202;</span></td></tr></table></div></td></tr></table></td></tr></tbody></table></td></tr>
  </tbody></table><table class="row row-4" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-size:auto"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-size:auto;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%"
  style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#edeff7;padding-left:40px;padding-right:40px;vertical-align:top;padding-top:0;padding-bottom:0;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div
  class="txtTinyMce-wrapper" style="font-size:14px;mso-line-height-alt:16.8px;color:#000;line-height:1.2;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif"><p style="margin:0;font-size:18px;letter-spacing:normal;mso-line-height-alt:16.8px">&nbsp;</p><p style="margin:0;font-size:18px;letter-spacing:normal"><span style="font-size:22px;"><strong>Forma de pagamento:</strong></span></p><p style="margin:0;font-size:18px;letter-spacing:normal;mso-line-height-alt:16.8px">&nbsp;</p><p
  style="margin:0;font-size:18px;letter-spacing:normal"><strong>Boleto bancário:</strong></p><p style="margin:0;font-size:18px;letter-spacing:normal;mso-line-height-alt:16.8px">&nbsp;</p><p style="margin:0;font-size:18px;letter-spacing:normal">Use a linha de código de barras abaixo para pagamento:</p><p style="margin:0;font-size:18px;letter-spacing:normal;mso-line-height-alt:16.8px">&nbsp;</p><p style="margin:0;font-size:18px;letter-spacing:normal">
  <span style="color:#2d4f83;"><strong>Teste</strong></span></p><p style="margin:0;font-size:18px;letter-spacing:normal;mso-line-height-alt:16.8px">&nbsp;</p><p style="margin:0;font-size:18px;letter-spacing:normal"><br>Ou, se preferir, é só acessar o seu boleto clicando no botão aqui embaixo:</p></div></div></td></tr></table><table class="button_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation"
  style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-bottom:35px;padding-left:10px;padding-right:10px;padding-top:30px;text-align:center"><div class="alignment" align="center">
  <!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="#" style="height:46px;width:170px;v-text-anchor:middle;" arcsize="131%" stroke="false" fillcolor="#00afec"><w:anchorlock/><v:textbox inset="0px,0px,0px,0px"><center style="color:#000000; font-family:Tahoma, Verdana, sans-serif; font-size:18px"><![endif]-->
  <a href="Teste" target="_blank" style="text-decoration:none;display:inline-block;color:#000000;background-color:#00afec;border-radius:60px;width:auto;border-top:1px solid #00afec;font-weight:400;border-right:1px solid #00afec;border-bottom:1px solid #00afec;border-left:1px solid #00afec;padding-top:5px;padding-bottom:5px;font-family:'Roboto', Tahoma, Verdana, Segoe, sans-serif;text-align:center;mso-border-alt:none;word-break:keep-all;"><span style="padding-left:25px;padding-right:25px;font-size:18px;display:inline-block;letter-spacing:normal;"><span dir="ltr" style="font-size: 16px; word-break: break-word; line-height: 2; mso-line-height-alt: 32px;"><strong><span style="font-size: 18px;" dir="ltr" data-mce-style="font-size: 18px;">Acessar </span></strong><strong><span style="font-size: 18px;" dir="ltr" data-mce-style="font-size: 18px;">Boleto</span></strong></span></span></a>
  <!--[if mso]></center></v:textbox></v:roundrect><![endif]--></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-5" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation"
  style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-left:40px;padding-right:40px;vertical-align:top;padding-top:25px;padding-bottom:10px;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation"
  style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:14px;mso-line-height-alt:16.8px;color:#2b2b2b;line-height:1.2;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif"><p style="margin:0;font-size:18px;letter-spacing:normal"><span style="font-size:22px;"><strong><span style>Pedido Teste</span></strong></span></p><p
  style="margin:0;font-size:18px;letter-spacing:normal;mso-line-height-alt:16.8px">&nbsp;</p></div></div></td></tr></table><table class="image_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center" style="line-height:10px">
  <a href="#" target="_blank" style="outline:none" tabindex="-1"><img class="big" src="https://braze-images.com/appboy/communication/assets/image_assets/images/61e20092a28e7c56ab9066cc/original.jpg?1642201234" style="display:block;height:auto;border:0;width:520px;max-width:100%" width="520"></a></div></td></tr></table><table class="divider_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation"
  style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-bottom:30px;padding-left:10px;padding-right:10px;padding-top:30px"><div class="alignment" align="center"><table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="divider_inner" style="font-size:1px;line-height:1px;border-top:1px solid #bbb"><span>&#8202;</span></td></tr></table></div></td></tr></table></td></tr></tbody></table>
  </td></tr></tbody></table><table class="row row-6" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;border-radius:0;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%"
  style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#fff;padding-left:40px;padding-right:40px;vertical-align:top;padding-top:20px;padding-bottom:30px;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="heading_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="text-align:center;width:100%"><h1
  style="margin:0;color:#2b2b2b;direction:ltr;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif;font-size:22px;font-weight:400;letter-spacing:normal;line-height:120%;text-align:center;margin-top:0;margin-bottom:0"><strong>Esse email foi útil pra você?</strong></h1></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-7" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0">
  <tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;border-radius:0;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#fff;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-2" width="100%"
  border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0;padding-bottom:15px"><div class="alignment" align="center" style="line-height:10px"><a href="https://forms.gle/4ABKNdhmZXXeTJsZ6" target="_blank" style="outline:none" tabindex="-1"><img src="https://braze-images.com/appboy/communication/assets/image_assets/images/6306c3436cc77a7adb1bcef1/original.jpg?1661387587"
  style="display:block;height:auto;border:0;width:225px;max-width:100%" width="225"></a></div></td></tr></table></td><td class="column column-2" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#fff;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td
  class="pad" style="width:100%;padding-right:0;padding-left:0;padding-bottom:15px"><div class="alignment" align="center" style="line-height:10px"><a href="https://forms.gle/VevqrrWwPpjxJvsF6" target="_blank" style="outline:none" tabindex="-1"><img src="https://braze-images.com/appboy/communication/assets/image_assets/images/6306c383e066f025100ec811/original.jpg?1661387651" style="display:block;height:auto;border:0;width:225px;max-width:100%" width="225"></a></div></td></tr></table></td></tr>
  </tbody></table></td></tr></tbody></table><table class="row row-8" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#2b2b2b;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%"
  style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-left:40px;padding-right:40px;vertical-align:top;padding-top:40px;padding-bottom:40px;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="heading_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-bottom:40px;text-align:center;width:100%"><h1
  style="margin:0;color:#fff;direction:ltr;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif;font-size:26px;font-weight:400;letter-spacing:normal;line-height:120%;text-align:left;margin-top:0;margin-bottom:0"><strong>A Jyula é seu amigo<br>para todas as horas!</strong></h1></td></tr></table><table class="text_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div
  style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:14px;mso-line-height-alt:16.8px;color:#fff;line-height:1.2;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif"><p style="margin:0;font-size:16px;letter-spacing:normal"><span style="font-size:12px;">Esse é um e-mail automático, então não conseguimos ver suas respostas.</span><br>
  <span style="font-size:12px;">Caso precise de alguma ajuda, é só chamar o <a href="#" target="_blank" rel="noopener" style="color: #00afec;">Jyulano Whatsapp.</a></span></p></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-9" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content"
  align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#2b2b2b;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="25%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-left:30px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0"
  role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-top:10px;width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center" style="line-height:10px"><a href="#" target="_blank" style="outline:none" tabindex="-1"><img src="https://appboy-images.com/appboy/communication/assets/image_assets/images/6153912ae150cb1fb018f78b/original.png?1632866602"
  style="display:block;height:auto;border:0;width:60px;max-width:100%" width="60"></a></div></td></tr></table></td><td class="column column-2" width="16.666666666666668%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td
  class="pad" style="padding-top:10px;width:100%;padding-right:0;padding-left:0"><div class="alignment" align="left" style="line-height:10px"><a href="#" target="_blank" style="outline:none" tabindex="-1"><img src="https://appboy-images.com/appboy/communication/assets/image_assets/images/6153912a6b8fb9341a3de794/original.png?1632866602" style="display:block;height:auto;border:0;width:60px;max-width:100%" width="60"></a></div></td></tr></table></td><td
  class="column column-3" width="16.666666666666668%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-top:10px;width:100%;padding-right:0;padding-left:0"><div class="alignment" align="left"
  style="line-height:10px"><a href="#" target="_blank" style="outline:none" tabindex="-1"><img src="https://appboy-images.com/appboy/communication/assets/image_assets/images/6153912aee559026bd831d0e/original.png?1632866602" style="display:block;height:auto;border:0;width:65px;max-width:100%" width="65"></a></div></td></tr></table></td><td class="column column-4" width="16.666666666666668%"
  style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-top:10px;width:100%;padding-right:0;padding-left:0"><div class="alignment" align="left" style="line-height:10px">
  <a href="#" target="_blank" style="outline:none" tabindex="-1"><img src="https://appboy-images.com/appboy/communication/assets/image_assets/images/6153912a3d0f9432f4c84c36/original.png?1632866602" style="display:block;height:auto;border:0;width:60px;max-width:100%" width="60"></a></div></td></tr></table></td><td class="column column-5" width="25%"
  style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-left:40px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><div class="spacer_block" style="height:20px;line-height:0;font-size:1px">&#8202;</div></td></tr></tbody></table></td></tr></tbody></table><table class="row row-10" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table
  class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#2b2b2b;color:#000;width:600px" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-left:40px;padding-right:40px;vertical-align:top;padding-top:40px;padding-bottom:60px;border-top:0;border-right:0;border-bottom:0;border-left:0"><table
  class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:14px;mso-line-height-alt:16.8px;color:#fff;line-height:1.2;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif"><p style="margin:0;font-size:16px;letter-spacing:normal">
  <span style="font-size:12px;">Caso não queira mais receber nossos emails, <a href="#" target="_blank" style="text-decoration: underline; color: #00afec;" rel="noopener">descadastre-se</a>.</span></p></div></div></td></tr></table><table class="text_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"
  style="padding-bottom:20px;padding-top:40px"><div style="font-family:sans-serif"><div class="txtTinyMce-wrapper" style="font-size:14px;mso-line-height-alt:16.8px;color:#000;line-height:1.2;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif"><p style="margin:0;font-size:16px;letter-spacing:normal"><span style="font-size:12px;">Jyula O Melhor Amigo.  34.697.707/0001-10.<br>Alameda Vicente Pinzon, CEP 04547-130, número 54, Vila Olímpia, São Paulo SP</span></p></div></div></td>
  </tr></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><!-- End --></body></html>
  `;
}

export default ExampleTemplate;
